name = "revelio"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "b1e67ec8062f4b0baf93bc99eb035406"

[[kv_namespaces]]
binding = "REFRESH_KV"
id = "3744363cf35b409b965f9d2c1e6a6932"

[[kv_namespaces]]
binding = "RESET_KV"
id = "07d98027000a4701943052ab57653688"

[[d1_databases]]
binding = "DB"
database_name = "revelio-db"
database_id = "3bd2c485-0c2b-4612-843c-2151678db166"
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "production"

[triggers]
crons = ["*/15 * * * *"]
