name = "revelio-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "REPLACE_WITH_KV_ID"

[[kv_namespaces]]
binding = "REFRESH_KV"
id = "REPLACE_WITH_REFRESH_KV_ID"

[[kv_namespaces]]
binding = "RESET_KV"
id = "REPLACE_WITH_RESET_KV_ID"

[[d1_databases]]
binding = "DB"
database_name = "revelio-db"
database_id = "REPLACE_WITH_D1_ID"

[vars]
ENVIRONMENT = "development"
JWT_SECRET = "REPLACE_WITH_A_STRONG_RANDOM_SECRET_MIN_32_CHARS"
RESEND_API_KEY = "REPLACE_WITH_RESEND_API_KEY"